
import { Plan } from "../types";

export interface MockKeyData {
    code: string;
    durationDays: number;
    type: Plan;
}

// FILE 1: THE DATABASE OF KEYS
// These are the keys generated by the "system".
export const MOCK_KEYS: MockKeyData[] = [
    { code: "gtayr1super2025", durationDays: 30, type: "pro" },  // 30 Days
    { code: "bematopius", durationDays: 15, type: "pro" },     // 15 Days
    { code: "amirkrut", durationDays: 20, type: "pro" }        // 20 Days
];